version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./backend:/app/backend
      - ./start.sh:/app/start.sh
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    command: ./start.sh
    depends_on:
      - redis
      - pgdb

  pgdb:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb_local
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  portfolio_service:
    build:
      context: ./backend/portfolio_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./backend/portfolio_service:/app
      - /app/node_modules
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://mongodb:27017/portfolio_db
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend/reactjs
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/reactjs/stock-auth-tester:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - REACT_APP_STOCK_URL=http://localhost:5002
      - REACT_APP_PORTFOLIO_URL=http://localhost:5003
    command: npm start

volumes:
  pgdata:
  mongodata:
